//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    
    
    public class TTRD_CDS
    {
        
        private string _fee_periodic_fst_pay_date;
        
        private double _fee_periodic_fst_pay_amount;
        
        private string _settlement_type;
        
        private string _st_physical_asset_type;
        
        private string _debt_properties;
        
        private double _ce_bankruptcy;
        
        private double _ce_default;
        
        private double _ce_default_init_amt;
        
        private double _ce_default_defer_period;
        
        private double _ce_default_is_following;
        
        private double _ce_accelerate_mtr;
        
        private double _ce_accelerate_amt;
        
        private double _ce_potential_accelerate_mtr;
        
        private double _ce_potential_accelerate_amt;
        
        private double _ce_restructur;
        
        private double _ce_restructur_amt;
        
        private double _ce_restructur_min_holder;
        
        private double _ce_other;
        
        private double _st_cash_set_type;
        
        private double _st_cash_recovery_rate;
        
        private string _st_cash_offer_type;
        
        private string _st_cash_offer_time;
        
        private string _st_cash_valuation_type;
        
        private string _debt_type;
        
        private string _st_physical_asset_properties;
        
        private string _imp_date;
        
        private double _pipe_id;
        
        private string _update_time;
        
        private double _i_id;
        
        private string _cure_code;
        
        private string _other_debt_type;
        
        private string _other_debt_properties;
        
        private string _other_credit_event;
        
        private string _other_valuation_type;
        
        private string _other_offer_type;
        
        private string _other_asset_type;
        
        private string _other_asset_properties;
        
        private string _relatedwarrant_i_code;
        
        private string _relatedwarrant_a_type;
        
        private string _relatedwarrant_m_type;
        
        private string _valuation_type;
        
        private string _mtr_date_include;
        
        private string _i_code;
        
        private string _a_type;
        
        private string _m_type;
        
        private string _start_date;
        
        private string _effective_date;
        
        private string _mtr_date;
        
        private string _mtr_date_conv;
        
        private string _term;
        
        private string _country;
        
        private string _currency;
        
        private string _q_type;
        
        private string _i_name;
        
        private string _p_class;
        
        private string _p_type;
        
        private string _s_type;
        
        private string _fpml;
        
        private double _amount;
        
        private double _par_value;
        
        private double _reference_price;
        
        private string _calendar;
        
        private string _conv;
        
        private string _reference_entity_name;
        
        private string _reference_entity_id;
        
        private string _reference_obligation_i_code;
        
        private string _reference_obligation_a_type;
        
        private string _reference_obligation_m_type;
        
        private string _clear_type;
        
        private string _calculation_agent;
        
        private double _credit_spread;
        
        private double _reference_recovery_rate;
        
        private string _discount_irc_code;
        
        private double _fee_upfront_rate;
        
        private double _fee_upfront_amount;
        
        private double _fee_initial_return_amount;
        
        private string _fee_initial_pay_date;
        
        private double _fee_initial_amount;
        
        private string _fee_initial_is_payer;
        
        private string _fee_periodic_pay_freq;
        
        private double _fee_periodic_fixed_rate;
        
        private string _fee_periodic_daycount;
        
        public virtual string FEE_PERIODIC_FST_PAY_DATE
        {
            get
            {
                return this._fee_periodic_fst_pay_date;
            }
            set
            {
                this._fee_periodic_fst_pay_date = value;
            }
        }
        
        public virtual double FEE_PERIODIC_FST_PAY_AMOUNT
        {
            get
            {
                return this._fee_periodic_fst_pay_amount;
            }
            set
            {
                this._fee_periodic_fst_pay_amount = value;
            }
        }
        
        public virtual string SETTLEMENT_TYPE
        {
            get
            {
                return this._settlement_type;
            }
            set
            {
                this._settlement_type = value;
            }
        }
        
        public virtual string ST_PHYSICAL_ASSET_TYPE
        {
            get
            {
                return this._st_physical_asset_type;
            }
            set
            {
                this._st_physical_asset_type = value;
            }
        }
        
        public virtual string DEBT_PROPERTIES
        {
            get
            {
                return this._debt_properties;
            }
            set
            {
                this._debt_properties = value;
            }
        }
        
        public virtual double CE_BANKRUPTCY
        {
            get
            {
                return this._ce_bankruptcy;
            }
            set
            {
                this._ce_bankruptcy = value;
            }
        }
        
        public virtual double CE_DEFAULT
        {
            get
            {
                return this._ce_default;
            }
            set
            {
                this._ce_default = value;
            }
        }
        
        public virtual double CE_DEFAULT_INIT_AMT
        {
            get
            {
                return this._ce_default_init_amt;
            }
            set
            {
                this._ce_default_init_amt = value;
            }
        }
        
        public virtual double CE_DEFAULT_DEFER_PERIOD
        {
            get
            {
                return this._ce_default_defer_period;
            }
            set
            {
                this._ce_default_defer_period = value;
            }
        }
        
        public virtual double CE_DEFAULT_IS_FOLLOWING
        {
            get
            {
                return this._ce_default_is_following;
            }
            set
            {
                this._ce_default_is_following = value;
            }
        }
        
        public virtual double CE_ACCELERATE_MTR
        {
            get
            {
                return this._ce_accelerate_mtr;
            }
            set
            {
                this._ce_accelerate_mtr = value;
            }
        }
        
        public virtual double CE_ACCELERATE_AMT
        {
            get
            {
                return this._ce_accelerate_amt;
            }
            set
            {
                this._ce_accelerate_amt = value;
            }
        }
        
        public virtual double CE_POTENTIAL_ACCELERATE_MTR
        {
            get
            {
                return this._ce_potential_accelerate_mtr;
            }
            set
            {
                this._ce_potential_accelerate_mtr = value;
            }
        }
        
        public virtual double CE_POTENTIAL_ACCELERATE_AMT
        {
            get
            {
                return this._ce_potential_accelerate_amt;
            }
            set
            {
                this._ce_potential_accelerate_amt = value;
            }
        }
        
        public virtual double CE_RESTRUCTUR
        {
            get
            {
                return this._ce_restructur;
            }
            set
            {
                this._ce_restructur = value;
            }
        }
        
        public virtual double CE_RESTRUCTUR_AMT
        {
            get
            {
                return this._ce_restructur_amt;
            }
            set
            {
                this._ce_restructur_amt = value;
            }
        }
        
        public virtual double CE_RESTRUCTUR_MIN_HOLDER
        {
            get
            {
                return this._ce_restructur_min_holder;
            }
            set
            {
                this._ce_restructur_min_holder = value;
            }
        }
        
        public virtual double CE_OTHER
        {
            get
            {
                return this._ce_other;
            }
            set
            {
                this._ce_other = value;
            }
        }
        
        public virtual double ST_CASH_SET_TYPE
        {
            get
            {
                return this._st_cash_set_type;
            }
            set
            {
                this._st_cash_set_type = value;
            }
        }
        
        public virtual double ST_CASH_RECOVERY_RATE
        {
            get
            {
                return this._st_cash_recovery_rate;
            }
            set
            {
                this._st_cash_recovery_rate = value;
            }
        }
        
        public virtual string ST_CASH_OFFER_TYPE
        {
            get
            {
                return this._st_cash_offer_type;
            }
            set
            {
                this._st_cash_offer_type = value;
            }
        }
        
        public virtual string ST_CASH_OFFER_TIME
        {
            get
            {
                return this._st_cash_offer_time;
            }
            set
            {
                this._st_cash_offer_time = value;
            }
        }
        
        public virtual string ST_CASH_VALUATION_TYPE
        {
            get
            {
                return this._st_cash_valuation_type;
            }
            set
            {
                this._st_cash_valuation_type = value;
            }
        }
        
        public virtual string DEBT_TYPE
        {
            get
            {
                return this._debt_type;
            }
            set
            {
                this._debt_type = value;
            }
        }
        
        public virtual string ST_PHYSICAL_ASSET_PROPERTIES
        {
            get
            {
                return this._st_physical_asset_properties;
            }
            set
            {
                this._st_physical_asset_properties = value;
            }
        }
        
        public virtual string IMP_DATE
        {
            get
            {
                return this._imp_date;
            }
            set
            {
                this._imp_date = value;
            }
        }
        
        public virtual double PIPE_ID
        {
            get
            {
                return this._pipe_id;
            }
            set
            {
                this._pipe_id = value;
            }
        }
        
        public virtual string UPDATE_TIME
        {
            get
            {
                return this._update_time;
            }
            set
            {
                this._update_time = value;
            }
        }
        
        public virtual double I_ID
        {
            get
            {
                return this._i_id;
            }
            set
            {
                this._i_id = value;
            }
        }
        
        public virtual string CURE_CODE
        {
            get
            {
                return this._cure_code;
            }
            set
            {
                this._cure_code = value;
            }
        }
        
        public virtual string OTHER_DEBT_TYPE
        {
            get
            {
                return this._other_debt_type;
            }
            set
            {
                this._other_debt_type = value;
            }
        }
        
        public virtual string OTHER_DEBT_PROPERTIES
        {
            get
            {
                return this._other_debt_properties;
            }
            set
            {
                this._other_debt_properties = value;
            }
        }
        
        public virtual string OTHER_CREDIT_EVENT
        {
            get
            {
                return this._other_credit_event;
            }
            set
            {
                this._other_credit_event = value;
            }
        }
        
        public virtual string OTHER_VALUATION_TYPE
        {
            get
            {
                return this._other_valuation_type;
            }
            set
            {
                this._other_valuation_type = value;
            }
        }
        
        public virtual string OTHER_OFFER_TYPE
        {
            get
            {
                return this._other_offer_type;
            }
            set
            {
                this._other_offer_type = value;
            }
        }
        
        public virtual string OTHER_ASSET_TYPE
        {
            get
            {
                return this._other_asset_type;
            }
            set
            {
                this._other_asset_type = value;
            }
        }
        
        public virtual string OTHER_ASSET_PROPERTIES
        {
            get
            {
                return this._other_asset_properties;
            }
            set
            {
                this._other_asset_properties = value;
            }
        }
        
        public virtual string RELATEDWARRANT_I_CODE
        {
            get
            {
                return this._relatedwarrant_i_code;
            }
            set
            {
                this._relatedwarrant_i_code = value;
            }
        }
        
        public virtual string RELATEDWARRANT_A_TYPE
        {
            get
            {
                return this._relatedwarrant_a_type;
            }
            set
            {
                this._relatedwarrant_a_type = value;
            }
        }
        
        public virtual string RELATEDWARRANT_M_TYPE
        {
            get
            {
                return this._relatedwarrant_m_type;
            }
            set
            {
                this._relatedwarrant_m_type = value;
            }
        }
        
        public virtual string VALUATION_TYPE
        {
            get
            {
                return this._valuation_type;
            }
            set
            {
                this._valuation_type = value;
            }
        }
        
        public virtual string MTR_DATE_INCLUDE
        {
            get
            {
                return this._mtr_date_include;
            }
            set
            {
                this._mtr_date_include = value;
            }
        }
        
        public virtual string I_CODE
        {
            get
            {
                return this._i_code;
            }
            set
            {
                this._i_code = value;
            }
        }
        
        public virtual string A_TYPE
        {
            get
            {
                return this._a_type;
            }
            set
            {
                this._a_type = value;
            }
        }
        
        public virtual string M_TYPE
        {
            get
            {
                return this._m_type;
            }
            set
            {
                this._m_type = value;
            }
        }
        
        public virtual string START_DATE
        {
            get
            {
                return this._start_date;
            }
            set
            {
                this._start_date = value;
            }
        }
        
        public virtual string EFFECTIVE_DATE
        {
            get
            {
                return this._effective_date;
            }
            set
            {
                this._effective_date = value;
            }
        }
        
        public virtual string MTR_DATE
        {
            get
            {
                return this._mtr_date;
            }
            set
            {
                this._mtr_date = value;
            }
        }
        
        public virtual string MTR_DATE_CONV
        {
            get
            {
                return this._mtr_date_conv;
            }
            set
            {
                this._mtr_date_conv = value;
            }
        }
        
        public virtual string TERM
        {
            get
            {
                return this._term;
            }
            set
            {
                this._term = value;
            }
        }
        
        public virtual string COUNTRY
        {
            get
            {
                return this._country;
            }
            set
            {
                this._country = value;
            }
        }
        
        public virtual string CURRENCY
        {
            get
            {
                return this._currency;
            }
            set
            {
                this._currency = value;
            }
        }
        
        public virtual string Q_TYPE
        {
            get
            {
                return this._q_type;
            }
            set
            {
                this._q_type = value;
            }
        }
        
        public virtual string I_NAME
        {
            get
            {
                return this._i_name;
            }
            set
            {
                this._i_name = value;
            }
        }
        
        public virtual string P_CLASS
        {
            get
            {
                return this._p_class;
            }
            set
            {
                this._p_class = value;
            }
        }
        
        public virtual string P_TYPE
        {
            get
            {
                return this._p_type;
            }
            set
            {
                this._p_type = value;
            }
        }
        
        public virtual string S_TYPE
        {
            get
            {
                return this._s_type;
            }
            set
            {
                this._s_type = value;
            }
        }
        
        public virtual string FPML
        {
            get
            {
                return this._fpml;
            }
            set
            {
                this._fpml = value;
            }
        }
        
        public virtual double AMOUNT
        {
            get
            {
                return this._amount;
            }
            set
            {
                this._amount = value;
            }
        }
        
        public virtual double PAR_VALUE
        {
            get
            {
                return this._par_value;
            }
            set
            {
                this._par_value = value;
            }
        }
        
        public virtual double REFERENCE_PRICE
        {
            get
            {
                return this._reference_price;
            }
            set
            {
                this._reference_price = value;
            }
        }
        
        public virtual string CALENDAR
        {
            get
            {
                return this._calendar;
            }
            set
            {
                this._calendar = value;
            }
        }
        
        public virtual string CONV
        {
            get
            {
                return this._conv;
            }
            set
            {
                this._conv = value;
            }
        }
        
        public virtual string REFERENCE_ENTITY_NAME
        {
            get
            {
                return this._reference_entity_name;
            }
            set
            {
                this._reference_entity_name = value;
            }
        }
        
        public virtual string REFERENCE_ENTITY_ID
        {
            get
            {
                return this._reference_entity_id;
            }
            set
            {
                this._reference_entity_id = value;
            }
        }
        
        public virtual string REFERENCE_OBLIGATION_I_CODE
        {
            get
            {
                return this._reference_obligation_i_code;
            }
            set
            {
                this._reference_obligation_i_code = value;
            }
        }
        
        public virtual string REFERENCE_OBLIGATION_A_TYPE
        {
            get
            {
                return this._reference_obligation_a_type;
            }
            set
            {
                this._reference_obligation_a_type = value;
            }
        }
        
        public virtual string REFERENCE_OBLIGATION_M_TYPE
        {
            get
            {
                return this._reference_obligation_m_type;
            }
            set
            {
                this._reference_obligation_m_type = value;
            }
        }
        
        public virtual string CLEAR_TYPE
        {
            get
            {
                return this._clear_type;
            }
            set
            {
                this._clear_type = value;
            }
        }
        
        public virtual string CALCULATION_AGENT
        {
            get
            {
                return this._calculation_agent;
            }
            set
            {
                this._calculation_agent = value;
            }
        }
        
        public virtual double CREDIT_SPREAD
        {
            get
            {
                return this._credit_spread;
            }
            set
            {
                this._credit_spread = value;
            }
        }
        
        public virtual double REFERENCE_RECOVERY_RATE
        {
            get
            {
                return this._reference_recovery_rate;
            }
            set
            {
                this._reference_recovery_rate = value;
            }
        }
        
        public virtual string DISCOUNT_IRC_CODE
        {
            get
            {
                return this._discount_irc_code;
            }
            set
            {
                this._discount_irc_code = value;
            }
        }
        
        public virtual double FEE_UPFRONT_RATE
        {
            get
            {
                return this._fee_upfront_rate;
            }
            set
            {
                this._fee_upfront_rate = value;
            }
        }
        
        public virtual double FEE_UPFRONT_AMOUNT
        {
            get
            {
                return this._fee_upfront_amount;
            }
            set
            {
                this._fee_upfront_amount = value;
            }
        }
        
        public virtual double FEE_INITIAL_RETURN_AMOUNT
        {
            get
            {
                return this._fee_initial_return_amount;
            }
            set
            {
                this._fee_initial_return_amount = value;
            }
        }
        
        public virtual string FEE_INITIAL_PAY_DATE
        {
            get
            {
                return this._fee_initial_pay_date;
            }
            set
            {
                this._fee_initial_pay_date = value;
            }
        }
        
        public virtual double FEE_INITIAL_AMOUNT
        {
            get
            {
                return this._fee_initial_amount;
            }
            set
            {
                this._fee_initial_amount = value;
            }
        }
        
        public virtual string FEE_INITIAL_IS_PAYER
        {
            get
            {
                return this._fee_initial_is_payer;
            }
            set
            {
                this._fee_initial_is_payer = value;
            }
        }
        
        public virtual string FEE_PERIODIC_PAY_FREQ
        {
            get
            {
                return this._fee_periodic_pay_freq;
            }
            set
            {
                this._fee_periodic_pay_freq = value;
            }
        }
        
        public virtual double FEE_PERIODIC_FIXED_RATE
        {
            get
            {
                return this._fee_periodic_fixed_rate;
            }
            set
            {
                this._fee_periodic_fixed_rate = value;
            }
        }
        
        public virtual string FEE_PERIODIC_DAYCOUNT
        {
            get
            {
                return this._fee_periodic_daycount;
            }
            set
            {
                this._fee_periodic_daycount = value;
            }
        }
    }
}
